pipeline {
    agent any

    stages {
        stage('Git Clone') {
            steps {
                git branch: 'master', credentialsId: 'aseongjun99', url: 'https://lab.ssafy.com/s12-webmobile1-sub1/S12P11A506.git'
            }
        }

        stage('Create application.yml') {
            steps {
                script {
                    // Jenkins Credentials에서 값 가져오기
                    dir('Backend/src/main/resources') {
                        sh """
                            cat > application.yml <<EOL
spring:
    application:
        name: muinus

    server:
        port: 8000

    batch:
        jdbc:
            initialize-schema: always
        job:
            enabled: false

    # 배치 DB
    datasource-meta:
        jdbc-url: ${BATCH_DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    datasource-data:
        jdbc-url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql:true
        database-platform: org.hibernate.dialect.MySQL8Dialect

    elasticsearch:
        rest:
            uris: http://elasticsearch:9200
            username: your_username  # 필요 시 설정
            password: your_password  # 필요 시 설정
    data:
        elasticsearch:
            repositories:
                enabled: true

    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ${KAKAO_OAUTH_CLIENT_ID}
                        redirect-uri: ${KAKAO_OAUTH_REDIRECT_URI}
                        authorization-grant-type: authorization_code
                        scope:
                            - profile_nickname
                            - account_email
                        client-name: Kakao
                        client-authentication-method: POST
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
    secretKey: ${JWT_SECRET_KEY}

    access:
        expiration: ${JWT_ACCESS_EXPIRATION}

    refresh:
        expiration: ${JWT_REFRESH_EXPIRATION}

EOL
                            """
                 }
              }
           }
        }

        stage('Build') {
            steps {
                dir('Backend') {
                    sh '''
                    chmod +x gradlew
                    ./gradlew clean bootJar
                    ls -a build/libs
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                    script {
                        sh 'pwd'
                        sh 'ls -a Backend/build/libs/'

                        sshPublisher(
                            publishers: [
                                sshPublisherDesc(
                                    configName: 'muinus-ec2',
                                    transfers: [
                                        sshTransfer(
                                            cleanRemote: false,
                                            excludes: '',
                                            sourceFiles: 'Backend/build/libs/*.jar',
                                            flatten: true,
                                            makeEmptyDirs: false,
                                            noDefaultExcludes: false,
                                            remoteDirectory: 'project/deploy/',
                                            remoteDirectorySDF: false,
                                            execCommand: '''
                                            sh /home/ubuntu/project/script/init_server.sh
                                            ''',
                                            execTimeout: 0
                                        )
                                    ],
                                    usePromotionTimestamp: false,
                                    useWorkspaceInPromotion: false,
                                    verbose: true
                                )
                            ]
                        )
                    }

            }
        }
    }
}
