pipeline {
    agent any

    stages {
        stage('Git Clone') {
            steps {
                git branch: 'master', credentialsId: 'aseongjun99', url: 'https://lab.ssafy.com/s12-webmobile1-sub1/S12P11A506.git'
            }
        }

        stage('Create application.yml') {
            steps {
                script {
                    // Jenkins Credentials에서 값 가져오기
                    def dbUrl = credentials('DB_URL')
                    def dbUser = credentials('DB_USER')
                    def dbPassword = credentials('DB_PASSWORD')

                    dir('Backend/src/main/resources') {
                        sh '''
                        cat > application.yml <<EOL
                        spring:
                          application:
                            name: muinus

                          datasource:
                            url: ${dbUrl}
                            username: ${dbUser}
                            password: ${dbPassword}
                            driver-class-name: com.mysql.cj.jdbc.Driver
                        EOL
                        '''
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir('Backend') {
                    sh 'chmod +x gradlew && ./gradlew clean bootJar'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sshPublisher(
                        publishers: [
                            sshPublisherDesc(
                                configName: 'muinus-ec2',
                                transfers: [
                                    sshTransfer(
                                        cleanRemote: false,
                                        excludes: '',
                                        flatten: false,
                                        makeEmptyDirs: false,
                                        noDefaultExcludes: false,
                                        patternSeparator: '[, ]+',
                                        remoteDirectory: '/home/ubuntu/project/deploy/',
                                        remoteDirectorySDF: false,
                                        removePrefix: 'build/libs',
                                        sourceFiles: 'build/libs/*.jar',
                                        execCommand: 'sh /home/ubuntu/project/script/init_server.sh',
                                        execTimeout: 120000
                                    )
                                ],
                                usePromotionTimestamp: false,
                                useWorkspaceInPromotion: false,
                                verbose: true
                            )
                        ]
                    )
                }
            }
        }
    }
}
